# Generated by Django 5.1.7 on 2025-04-04 20:59

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explain', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='member',
            index=models.Index(django.db.models.functions.text.Upper('name'), name='name_upper_idx'),
        ),
    ]
