# Generated by Django 5.1.7 on 2025-04-04 20:59

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('explain', '0002_member_name_upper_idx'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='member',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='name_search_idx'),
        ),
    ]
