# Generated by Django 5.1.7 on 2025-04-04 21:01

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explain', '0003_member_name_search_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='member',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass('name', name='gin_trgm_ops'), name='name_gin_idx'),
        ),
    ]
