# Generated by Django 5.1.7 on 2025-04-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explain', '0005_member_uid_search_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(models.F('data__document_no'), name='data__document_no_idx'),
        ),
    ]
