# Generated by Django 5.1.7 on 2025-04-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explain', '0007_document_data__document_no_search_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='member',
            index=models.Index(models.F('name'), condition=models.Q(('external_id__isnull', True)), name='name_no_external_id_idx'),
        ),
    ]
